services:
  backend:
    container_name: hey-sheldon-backend
    image: hey-sheldon-backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/config.json:/app/backend/config.json
      - hey-db:/app/backend/data
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "5100:5100"
    environment:
      - TZ=Asia/Jerusalem

  frontend:
    user: root
    container_name: hey-sheldon-frontend
    image: hey-sheldon-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    user: root
    image: certbot/certbot
    container_name: hey-sheldon-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  hey-db: