services:
  hey-server:
    container_name: hey-sheldon-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
        image: hey-sheldon-server:${TAG}
    restart: always
    volumes:
      - ./server/config.json:/app/server/config.json
      - hey-db:/app/server/hey.db
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "5100:5100"
    environment:
      - TZ=Asia/Jerusalem

  hey-client:
    container_name: hey-sheldon-client
    image: nginx:alpine
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./client/build:/usr/share/nginx/html:ro

volumes:
  hey-db: