services:
  server:
    container_name: hey-sheldon-server
    image: hey-sheldon-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server/config.json:/app/server/config.json
      - hey-db:/app/server/hey.db
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "5100:5100"
    environment:
      - TZ=Asia/Jerusalem

  client:
    user: root
    container_name: hey-sheldon-client
    image: hey-sheldon-client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    user: root
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - hey-sheldon-client
    entrypoint: >
      /bin/sh -c '
        trap exit TERM;
        while :; do
          certbot renew --deploy-hook "docker exec hey-sheldon-client nginx -s reload";
          sleep 12h & wait $${!};
        done
      '

volumes:
  hey-db: